
# importing from .env
spring.config.import=optional:file:.env[.properties]
spring.application.name=15_NUT_YOULONG_SR_SPRING_Homework003

server.port=${SERVER_PORT}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

springdoc.swagger-ui.operations-sorter=method


